### PR TITLE
fix(lapis): prevent errors for mutationsOverTime endpoint and potentially other endpoints

### LINKED ISSUE #1304: Mutations over time request sometimes throw RejectedExecutionException
Sometimes, when I run larger queries (see example query below) against the mutations over time endpoint, I get the following error message:

```
{
  "error": {
    "type": "about:blank",
    "title": "Internal Server Error",
    "status": 500,
    "detail": "java.lang.RuntimeException: Could not connect to silo: class java.util.concurrent.RejectedExecutionException Thread limit exceeded replacing blocked worker"
  },
  "info": {
    "dataVersion": null,
    "requestId": "cdf1f8f4-a8eb-4372-8045-6a2448cb8dd2",
    "requestInfo": "sars_cov-2_gisaid on lapis.cov-spectrum.org at 2025-08-05T20:43:09.303865461",
    "reportTo": "Please report to https://github.com/GenSpectrum/LAPIS/issues in case you encounter any unexpected issues. Please include the request ID and the requestInfo in your report.",
    "lapisVersion": "0.5.8",
    "siloVersion": "0.7.4"
  }
}
```

<details><summary>cURL request</summary>

```sh
curl --request POST \
  --url https://lapis.cov-spectrum.org/open/v2/component/nucleotideMutationsOverTime \
  --header 'Content-Type: application/json' \
  --data '{
  "filters": {
    
  },
  "includeMutations": ["A1C", "A1G", "A1T", "T2A", "T2C", "T2G", "T3A", "T3G", "A4C", "A4G", "A4T", "A4-", "G8A", "T10A", "T10G", "T13A", "T13C", "C20T", "C21T", "C28T", "C36T", "C37T", "C40T", "C44T", "C106T", "C140T", "C186T", "C203T", "C222T", "T232C", "C241T", "C313T", "C335T", "C337T", "C344T", "C346T", "G347A", "G373A", "C506T", "G509-", "G510-", "T511-", "C512-", "A513-", "T514-", "G515-", "T516-", "T517-", "A518-", "T519-", "G520-", "G521-", "T522-", "T523-", "G524-", "C556T", "C583T", "C589T", "C593T", "C635T", "T658A", "C664T", "T670G", "C673T", "C683T", "A686-", "A687G", "A687-", "G688-", "T689-", "C690-", "A691-", "T692-", "T693-", "T694-", "G709A", "C745T", "A761G", "C774T", "C775T", "C823T", "C829T", "C832T", "C835T", "C874T", "C875T", "C897A", "C900T", "C920T", "C925T", "C934T", "C936T", "G942A", "C958T", "T1016C", "C1060T", "C1063T", "T1075C", "C1093T", "C1102T", "A1124G", "C1150T", "C1170T", "T1183A", "C1191T", "C1221T", "C1263T", "C1267T", "T1285G", "C1288T", "C1302T", "C1314T", "C1348T", "T1368C", "C1385T", "C1387T", "C1392T", "C1420T", "C1426T", "C1427T", "C1441T", "C1473T", "C1514T", "C1519T", "T1537C", "C1594T", "C1609T", "C1627T", "A1674C", "C1684T", "C1714T", "C1722T", "C1758T", "G1820A", "G1874T", "C1884T", "G1895A", "C1912T", "C1919T", "G1954A", "C1968T", "C1973T", "C2003T", "C2037T", "C2040T", "C2061T", "C2062T", "C2091T", "C2094T", "C2110A", "C2110T", "C2113T", "G2144T", "C2189T", "C2197T", "C2232T", "A2276G", "C2295T", "C2334T", "C2358T", "C2388T", "A2431G", "C2445T", "C2455T", "G2458T", "C2485T", "C2488T", "C2509T", "C2536T", "C2570T", "A2611C", "A2618G", "C2644T", "C2695T", "T2698C", "C2710T", "C2788T", "C2790T", "C2862T", "C2881T", "G2890A", "C2915G", "C2937T", "A2966C", "C3037T", "T3055C", "C3096T", "T3124C", "C3140T", "C3157T", "C3165T", "C3176T", "C3177T", "A3196T", "C3244T", "G3259T", "C3261T", "C3267T", "C3411T", "G3431T", "T3565C", "C3602T", "C3619T", "G3620A", "C3653T", "C3688T", "C3695T", "A3722G", "C3737T", "C3743T", "A3763G", "C3768T", "C3784T", "C3787T", "T3814C", "C3817T", "C3832A", "G3871T", "C3874T", "G3896-", "T3897-", "T3898-", "T3913A", "C3923T", "G3939A", "G3939T", "C4012T", "C4021T", "C4084T", "G4184A", "T4192C", "C4202T", "C4230T", "A4236G", "G4255A", "C4276T", "C4321T", "C4331T", "T4342C", "A4364C", "C4423T", "C4456T", "C4540T", "C4543T", "C4551T", "T4579A", "C4582T", "C4586T", "C4633T", "C4683T", "C4752T", "C4754T", "C4755T", "C4784T", "C4795T", "C4832T", "C4890T", "C4891T", "C4893T", "C4921T", "C4927T", "C4999T", "C5055T", "G5063A", "C5144T", "C5173T", "C5178A", "C5178T", "T5179C", "G5180A", "T5182C", "C5183T", "C5184T", "T5188C", "C5192T", "C5221T", "G5230T", "C5239T", "T5278C", "C5284T", "C5301T", "C5310T", "A5331G", "T5338C", "C5365T", "C5392T", "A5431G", "T5465C", "C5467T", "C5497T", "C5512T", "C5526T", "C5544T", "G5567A", "C5575T", "C5581A", "C5622T", "G5629T", "C5654T", "C5672T", "C5730T", "G5739A", "C5770T", "C5784T", "C5806T", "C5812T", "C5822T", "C5826T", "C5833T", "C5850T", "C5869T", "C5884T", "C5907T", "C5986T", "C6026T", "C6027T", "C6031T", "C6040T", "C6070T", "C6145T", "A6183G", "C6196T", "C6255T", "C6285T", "C6286T", "C6310T", "C6312T", "C6317T", "C6336T", "C6354T", "C6401T", "C6402T", "C6449T", "C6472T", "G6513-", "T6514-", "T6515-", "C6525T", "G6536A", "C6538T", "C6539T", "C6541T", "C6543T", "C6568T", "C6573T", "A6590G", "C6606T", "A6626G", "C6628T", "C6629T", "C6633T", "C6636T", "C6638T", "A6679G", "C6701T", "C6720T", "C6730T", "C6781T", "C6794T", "C6896T", "C6941T", "C6968T", "C6982T", "C6990T", "C7006T", "C7011T", "C7086T", "C7113T", "C7119T", "C7162T", "C7165T", "C7267T", "C7279T", "T7297A", "C7318T", "G7393T", "C7420T", "T7438C", "C7528T", "A7590G", "C7594T", "C7609T", "C7639T", "G7675T", "C7728T", "C7732T", "C7735T", "C7749T", "C7764T", "C7765T", "G7798T", "C7834T", "A7842G", "C7851T", "C7869T", "G7936T", "C7945T", "C7948T", "C8016T", "T8050C", "C8092T", "C8109T", "C8140T", "C8247T", "C8251T", "T8263C", "C8290T", "C8293T", "C8299T", "C8318A", "C8320T", "C8326T", "C8344T", "T8362C", "G8371T", "C8389T", "G8393A", "C8407T", "C8616T", "C8619T", "C8655T", "C8683T", "C8733T", "C8802T", "C8814T", "C8818T", "A8898T", "C8917T", "C8950T", "C9042A", "C9073T", "C9112T", "C9142T", "C9166T", "C9169T", "G9220A", "C9223T", "A9235G", "C9246T", "C9286T", "C9298T", "A9301G", "C9319T", "C9344T", "T9352C", "A9424G", "A9424T", "C9430T", "C9532T", "C9534T", "C9559T", "C9565T", "A9587G", "C9592T", "C9611T", "C9693T", "T9697C", "C9724T", "C9778T", "C9803T", "C9808T", "C9857T", "C9891T", "T9919C", "C9943T", "C9967T", "C9979T", "C10029T", "C10030T", "C10036T", "C10078T", "C10138T", "C10156T", "C10183T", "C10186T", "C10198T", "C10207T", "C10228T", "C10252T", "C10279T", "C10296T", "A10323G", "C10369T", "C10376T", "T10387C", "C10432T", "C10440T", "G10447A", "C10449A", "C10450T", "C10507T", "C10537T", "C10582T", "C10594T", "C10615T", "C10650T", "C10681T", "C10702T", "T10738C", "C10741T", "C10789T", "C10833T", "C10834T", "A10861G", "G10870T", "C10894T", "C10969T", "A10978T", "C11003T", "C11020T", "G11042T", "C11074T", "G11083T", "C11095T", "C11124T", "C11152T", "C11173T", "C11200T", "T11288-", "C11289-", "T11290-", "G11291A", "G11291-", "G11292-", "T11293-", "T11294-", "T11295-", "T11296G", "T11296-", "C11518T", "G11527T", "A11537G", "C11575T", "C11620T", "C11653T", "C11668T", "C11674T", "C11681T", "C11704T", "G11727A", "C11747T", "C11758T", "A11782G", "T11795C", "C11824T", "C11833T", "C11941T", "C11956T", "C11962T", "T11968C", "C12025T", "C12049T", "C12068T", "C12073T", "C12076T", "G12080A", "C12085T", "C12100T", "C12115T", "C12119T", "A12174G", "G12208A", "C12253T", "T12304C", "C12400T", "C12439T", "C12459T", "C12473T", "C12484T", "C12513T", "C12525T", "G12600A", "C12616T", "C12624T", "C12651T", "A12666C", "C12781T", "C12789T", "C12815T", "C12823T", "G12832A", "C12880T", "G12892A", "C12933T", "C12970T", "C13011T", "C13019T", "C13115T", "C13119T", "A13121T", "C13170T", "A13222G", "C13225T", "C13247T", "C13252T", "C13255T", "C13280A", "C13297T", "C13335T", "T13339C", "C13356T", "C13366T", "C13378T", "C13384T", "G13427A", "C13432T", "A13444T", "C13458T", "C13487T", "C13517T", "C13536T", "C13554T", "C13620T", "C13647T", "C13665T", "A13712G", "C13721T", "C13730T", "C13761T", "T13804C", "C13860T", "C13862T", "C13994T", "C14117T", "C14120T", "C14178T", "C14183T", "C14184T", "C14189T", "C14220T", "C14267T", "G14268T", "C14358T", "C14396T", "C14408T", "C14478T", "T14508C", "T14565C", "C14599T", "C14649T", "C14676T", "T14700C", "C14708T", "C14724T", "C14790T", "T14799C", "C14805T", "C14877T", "C14925T", "C14937T", "T14961C", "C15026T", "A15036G", "C15141T", "C15222T", "C15237T", "C15240T", "G15372T", "T15417C", "C15540T", "G15543T", "C15579T", "C15654T", "C15656T", "C15660T", "C15714T", "C15720T", "C15738T", "T15750C", "T15756A", "A15759G", "C15763T", "C15810T", "C15830T", "A15942G", "C15951T", "C15952T", "C15960T", "T16077C", "C16092T", "C16111T", "T16224C", "C16293T", "C16308T", "A16311G", "C16323T", "C16332T", "C16338T", "C16362T", "T16374C", "C16376T", "T16404C", "G16405A", "C16428T", "A16474G", "C16575T", "C16596T", "T16600C", "T16692C", "C16767T", "C16768A", "C16887T", "C17004T", "C17010T", "G17122T", "T17166C", "C17304T", "G17334T", "C17410T", "C17430T", "C17436T", "C17502T", "C17550T", "T17619C", "C17676T", "G17679T", "G17721T", "C17733T", "C17745T", "C17746T", "C17766T", "T17781C", "T17835C", "C17977T", "T17982C", "C17999T", "C18032T", "C18060T", "C18086T", "C18129T", "C18131T", "T18159C", "C18162T", "A18163G", "C18175T", "T18177C", "C18248T", "C18252T", "C18264T", "T18300A", "C18312T", "G18318T", "C18326T", "C18329T", "C18348T", "C18388T", "C18395T", "C18400T", "C18431T", "C18440A", "C18457T", "T18471C", "C18486T", "C18490T", "A18492G", "C18501T", "C18508T", "C18526T", "T18547C", "C18555T", "C18568T", "C18570T", "C18647T", "C18657T", "G18674A", "C18687T", "C18744T", "C18747T", "C18788T", "C18828T", "C18877T", "C18888T", "C18894T", "C18912T", "C18928T", "G18960A", "C18981T", "C19011T", "C19017T", "T19026C", "C19029T", "C19032T", "A19137T", "C19151T", "C19164T", "C19170T", "C19172T", "C19185T", "C19263T", "C19269T", "T19305C", "C19374T", "C19512T", "C19524T", "C19554T", "C19572T", "C19586T", "C19602T", "G19669A", "C19716T", "A19722G", "T19725G", "C19763T", "C19875T", "C19884T", "C19955T", "C19983T", "C20016T", "A20055G", "G20060T", "C20104T", "C20132T", "C20133T", "C20148T", "C20178T", "C20233T", "T20367C", "C20402T", "C20404T", "C20436T", "C20451T", "A20481G", "C20483T", "C20544T", "G20578T", "C20628T", "C20703T", "A20712G", "C20719T", "G20730T", "C20759T", "C20762T", "T20799C", "C20823T", "C20844T", "T20865C", "C20930T", "C20946T", "C21057T", "C21077T", "G21123T", "A21137G", "C21156T", "G21255C", "G21255T", "C21302T", "C21304A", "G21305A", "C21306T", "C21365T", "A21446G", "C21575T", "T21584C", "C21590T", "C21595T", "T21610C", "C21614T", "C21618T", "C21621T", "C21622T", "G21624C", "C21627A", "T21632-", "T21633-", "A21634-", "C21635-", "C21636-", "C21637-", "C21638-", "C21639-", "T21640-", "G21641T", "G21641-", "C21642-", "A21643-", "C21646T", "A21651-", "T21652-", "T21653C", "T21653-", "C21654T", "C21654-", "T21655-", "T21656-", "T21657-", "C21658T", "C21691T", "C21707T", "C21711T", "C21721T", "C21727T", "C21736T", "T21737C", "T21738C", "T21740C", "C21742T", "G21746T", "T21752A", "T21756A", "C21762T", "T21765-", "A21766T", "A21766-", "C21767-", "A21768-", "T21769-", "G21770-", "T21771-", "C21772-", "G21776A", "C21789T", "C21811T", "C21815T", "C21816A", "C21846T", "C21855T", "C21859T", "T21864C", "A21865T", "G21893A", "C21928T", "G21941T", "T21943C", "C21952T", "G21987A", "T21992-", "A21993-", "T21994-", "T21995-", "A21996-", "C21997-", "C21998A", "C21998T", "C22000A", "C22000T", "A22005C", "A22005G", "T22016C", "A22019G", "G22021C", "G22021T", "T22032C", "C22033A", "A22034G", "A22036G", "C22075T", "C22082T", "T22085C", "C22088T", "G22104T", "A22106G", "A22107G", "A22108C", "A22110C", "G22111T", "G22113T", "A22115G", "A22116C", "A22116-", "T22117-", "T22118-", "C22120A", "C22120T", "G22131C", "G22132T", "T22165C", "A22194-", "T22195-", "T22196-", "T22197-", "T22200A", "T22200G", "C22208T", "C22264T", "G22272A", "G22272T", "A22278G", "C22281T", "C22295A", "C22323T", "C22326T", "C22329T", "G22335T", "C22350T", "C22353A", "C22388T", "C22414T", "C22432T", "C22450T", "C22480T", "C22498T", "T22501C", "A22556G", "C22564T", "G22567T", "C22570T", "G22577C", "G22578A", "C22591T", "C22594T", "C22597T", "G22599C", "C22624T", "A22629C", "C22674T", "T22679C", "C22686T", "A22688G", "C22689A", "C22716T", "C22747T", "G22770A", "G22775A", "A22786C", "C22792T", "T22795G", "G22801T", "G22813T", "T22835C", "C22858T", "G22865T", "C22879T", "A22881G", "T22882G", "C22883T", "T22884G", "A22893G", "G22895C", "T22896A", "T22896C", "T22896G", "G22898A", "A22910G", "C22916T", "T22917G", "T22926C", "T22928C", "T22928G", "T22930A", "T22942A", "T22972C", "T22981C", "C22986T", "C22987T", "G22992A", "C22993T", "A22994G", "C22995A", "C22995G", "C22995T", "T23005A", "G23006-", "G23007-", "T23008-", "G23009-", "T23010-", "T23011-", "G23012A", "T23018C", "T23019C", "A23021G", "C23029T", "C23039G", "A23055G", "A23063T", "T23075C", "C23086T", "C23114T", "A23148C", "C23185T", "C23191T", "C23202A", "G23222A", "G23236T", "C23248T", "C23271T", "C23277T", "G23285T", "T23377C", "A23403G", "A23416T", "C23422T", "C23423T", "C23525T", "T23560A", "G23593T", "C23595T", "A23598G", "T23599G", "T23600C", "C23601A", "C23601T", "C23604A", "C23604G", "G23608T", "G23611T", "C23613T", "C23625T", "C23635T", "C23638T", "C23673T", "C23683T", "C23707T", "C23758T", "C23854A", "G23856T", "C23896T", "C23929T", "G23948T", "C24023T", "C24034T", "G24095T", "C24109T", "T24127C", "C24130T", "C24337T", "T24364C", "C24370T", "C24378T", "C24381T", "C24382T", "G24386T", "C24418T", "A24424T", "C24442T", "T24469A", "C24734T", "A24819G", "A24820G", "G24821T", "C24844T", "C24863T", "C24865T", "G24872T", "T24892C", "C24904T", "C24912T", "C24989T", "C24990T", "A24999G", "C25000T", "C25006T", "G25012T", "C25046T", "C25083T", "G25088T", "C25096T", "A25122G", "C25163A", "C25207T", "G25234T", "G25249T", "G25266T", "C25276T", "T25285C", "C25324T", "C25339T", "C25350T", "G25352T", "G25354T", "A25359G", "C25378T", "C25413T", "C25416T", "G25440T", "C25452T", "G25455T", "G25456C", "C25460T", "C25463T", "C25469T", "G25471C", "T25473C", "G25483C", "G25489T", "G25500T", "T25502C", "C25504A", "T25510C", "C25521T", "G25523A", "G25527T", "C25546T", "C25549T", "C25553T", "C25566T", "C25571T", "C25572T", "C25578T", "C25583T", "C25584T", "C25587T", "G25593T", "G25595T", "C25603T", "C25609T", "C25613T", "C25614T", "G25617T", "C25624T", "C25626T", "A25636T", "G25647T", "T25652C", "C25658T", "C25680T", "C25688T", "C25693T", "G25699A", "C25703T", "T25705C", "C25708T", "C25710T", "C25714T", "C25721T", "C25728T", "C25731T", "A25758T", "C25803T", "C25889T", "G25906T", "C25916T", "C25925T", "G25947C", "A25983T", "C26010T", "C26013T", "C26022T", "C26028T", "C26029A", "C26058T", "C26060T", "C26078T", "C26110T", "C26111T", "C26151T", "G26155-", "T26156-", "T26157-", "C26195T", "C26256T", "C26270T", "C26313T", "T26485-", "G26529C", "T26531C", "A26555G", "C26577G", "C26607T", "A26610G", "C26625T", "C26645T", "C26681T", "G26709A", "C26735T", "C26753T", "C26801T", "T26819A", "C26822T", "C26833T", "G26840A", "C26858T", "C26873T", "C26882T", "C26885T", "C26894T", "C26895T", "C26907T", "C26936T", "G26951T", "T26957C", "C27002T", "C27005T", "C27059T", "C27092T", "C27110T", "C27128T", "C27131T", "C27143T", "C27247A", "C27247T", "A27259C", "T27288A", "C27294T", "C27297T", "A27372T", "G27382C", "A27383T", "T27384C", "C27389T", "C27434T", "C27476T", "T27484C", "A27507G", "C27509T", "C27513T", "C27549T", "T27568-", "T27569-", "T27570-", "A27571-", "G27572-", "C27573-", "A27574-", "C27575-", "T27576-", "C27577-", "A27578-", "A27579-", "T27580-", "T27581-", "T27582-", "G27583-", "C27584-", "T27585-", "T27586-", "T27587-", "T27588-", "G27589-", "C27590-", "T27592-", "T27594-", "C27595-", "G27598-", "A27599-", "C27600T", "C27600-", "G27601-", "G27602-", "C27603-", "G27604-", "T27605-", "A27606-", "A27607-", "A27608-", "A27609-", "C27610-", "A27611-", "C27612-", "G27613-", "T27614-", "C27615-", "T27616-", "A27617-", "T27618-", "C27619-", "G27621-", "C27630T", "A27633G", "C27654T", "C27679T", "C27741T", "C27752T", "A27770G", "T27792-", "T27793-", "C27804T", "C27807T", "A27809G", "T27810C", "A27831G", "C27847T", "C27849T", "C27881T", "C27883T", "C27923T", "C27944T", "C27945T", "G27948T", "C27982T", "G28001T", "C28045T", "C28054T", "A28065-", "T28066-", "T28067-", "G28068-", "A28069-", "A28070-", "T28071-", "T28072-", "C28076T", "G28077T", "G28079T", "C28087T", "G28089-", "G28090-", "T28091-", "T28092-", "C28093T", "C28093-", "T28094A", "T28094-", "A28095-", "A28096-", "A28097-", "T28098-", "C28153T", "T28251G", "C28253T", "A28254C", "A28254-", "A28271T", "C28291A", "T28297C", "C28310T", "C28311T", "C28312T", "C28344T", "G28362-", "A28363-", "G28364-", "A28365-", "A28366-", "C28367-", "G28368-", "C28369-", "A28370-", "G28378T", "T28382C", "G28396A", "C28399T", "G28423A", "C28432T", "C28453T", "C28462T", "A28468G", "C28471T", "T28474C", "C28507T", "T28516C", "C28519T", "T28582C", "C28603T", "C28606T", "G28628A", "C28651T", "C28657T", "C28674T", "C28677T", "T28693C", "C28695T", "T28705C", "C28708T", "C28714T", "C28717T", "C28720T", "G28727T", "C28732T", "C28744T", "C28770T", "C28791T", "A28792T", "G28798A", "T28813C", "C28849T", "T28861C", "G28872A", "G28875A", "A28877T", "G28878C", "G28881A", "G28882A", "G28883C", "G28884A", "G28884C", "G28895T", "T28924C", "C28928T", "G28942A", "C28948T", "C28957T", "C28958A", "C29002T", "C29077T", "C29085T", "C29095T", "C29119T", "G29134T", "C29137T", "C29144T", "C29149T", "C29167T", "C29171T", "T29185C", "C29200T", "C29218T", "G29227T", "C29250A", "C29253T", "C29272T", "C29284T", "C29296T", "C29311T", "C29353T", "C29358T", "C29367T", "C29370T", "C29409T", "C29420T", "C29421T", "G29449T", "T29464C", "C29485T", "A29510C", "C29541T", "G29543T", "C29545T", "C29555T", "A29567G", "C29580T", "T29581-", "T29604C", "C29614T", "C29627T", "G29628A", "T29633C", "C29635T", "T29637A", "C29640T", "C29642T", "A29664G", "T29665C", "C29666T", "A29671G", "C29675T", "A29700G", "G29706A", "C29708T", "A29716T", "G29717A", "T29728-", "T29729-", "C29730-", "A29731-", "C29732-", "C29733-", "G29734-", "A29735-", "G29736-", "G29737-", "C29738-", "C29739-", "A29740-", "C29741-", "G29742-", "C29743-", "G29744-", "G29745-", "A29746-", "G29747-", "T29748-", "A29749-", "C29750-", "G29751-", "A29752-", "T29753-", "C29754-", "G29755-", "A29756-", "G29757-", "T29758-", "G29759C", "G29759T", "G29759-", "T29760-", "A29761-", "C29762T", "C29762-", "A29763-", "G29764-", "T29765-", "G29766-", "A29767-", "A29768-", "C29769T", "C29769-", "A29770-", "A29771-", "T29772-", "G29773-", "C29774T", "C29774-", "T29775-", "A29776-", "G29779T", "G29781T", "C29836T", "T29856C", "A29865T", "A29865-", "A29866C", "A29866-", "T29867A", "T29867G", "T29867-", "G29868A", "G29868C", "G29868T", "G29868-", "A29869G", "A29869T", "A29869-", "C29870A"],
  "dateRanges": [
    {"dateFrom":"2025-02-03","dateTo":"2025-02-09"},
    {"dateFrom":"2025-02-10","dateTo":"2025-02-16"},
    {"dateFrom":"2025-02-17","dateTo":"2025-02-23"},
    {"dateFrom":"2025-02-24","dateTo":"2025-03-02"},
    {"dateFrom":"2025-03-03","dateTo":"2025-03-09"},
    {"dateFrom":"2025-03-10","dateTo":"2025-03-16"},
    {"dateFrom":"2025-03-17","dateTo":"2025-03-23"},
    {"dateFrom":"2025-03-24","dateTo":"2025-03-30"},
    {"dateFrom":"2025-03-31","dateTo":"2025-04-06"},
    {"dateFrom":"2025-04-07","dateTo":"2025-04-13"},
    {"dateFrom":"2025-04-14","dateTo":"2025-04-20"},
    {"dateFrom":"2025-04-21","dateTo":"2025-04-27"},
    {"dateFrom":"2025-04-28","dateTo":"2025-05-04"},
    {"dateFrom":"2025-05-05","dateTo":"2025-05-11"},
    {"dateFrom":"2025-05-12","dateTo":"2025-05-18"},
    {"dateFrom":"2025-05-19","dateTo":"2025-05-25"},
    {"dateFrom":"2025-05-26","dateTo":"2025-06-01"},
    {"dateFrom":"2025-06-02","dateTo":"2025-06-08"},
    {"dateFrom":"2025-06-09","dateTo":"2025-06-15"},
    {"dateFrom":"2025-06-16","dateTo":"2025-06-22"},
    {"dateFrom":"2025-06-23","dateTo":"2025-06-29"},
    {"dateFrom":"2025-06-30","dateTo":"2025-07-06"},
    {"dateFrom":"2025-07-07","dateTo":"2025-07-13"},
    {"dateFrom":"2025-07-14","dateTo":"2025-07-20"},
    {"dateFrom":"2025-07-21","dateTo":"2025-07-27"}
  ],
  "dateField": "date"
}'
```
</summary>

### PR DESCRIPTION
**Pull request by fhennig**
resolves #1304 

In #1304 we had the problem of first getting `class java.util.concurrent.RejectedExecutionException Thread limit exceeded replacing blocked worker`. This was raised inside `httpClient.send`. According to my research, by default, the `ForkJoinPool.commonPool()` is used by many JDKs, which is the same Pool also used by `parallelStream`, which is used in the `mutationsOverTime` endpoint to create all the SILO requests in parallel. That pool has an internal spare thread limit, which I think was crossed due to too many blocked threads. Giving the httpClient its own Executor and thread pool fixed this problem.

Second, we got a `GOAWAY` response from the nginx proxy in front of the SILO. nginx closes a connection after 1000 requests (configurable, but not recommended to set higher than 1000). We no retry after a `GOAWAY` response.

## PR Checklist
- [x] All necessary documentation has been adapted.
- ~~The implemented feature is covered by an appropriate test.~~

### CODE REVIEW

File: lapis/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt [hunk 1]
```diff
@@ -172,9 +177,21 @@ open class CachedSiloClient(
             .build()
 
         val response = try {
-            httpClient.send(request, bodyHandler)
+            try {
+                httpClient.send(request, bodyHandler)
+            } catch (ioException: IOException) {
+                // When sending requests to SILO behind an NGINX, NGINX will send GOAWAY
+                // after 1000 requests through the same connection. The HTTPClient will
+                // retry GET requests (idempotent) but not PUT requests. Our PUT requests
```
Comment (fengelniederhammer) [inline lapis/src/main/kotlin/org/genspectrum/lapis/silo/SiloClient.kt:185]: Do we use PUT?
```suggestion
                // retry GET requests (idempotent) but not POST requests. Our POST requests
```
