### PR TITLE
fix(lapis): advanced queries: make `.regex` case-insensitive

### LINKED ISSUE #1187: Make advanced queries case insensitive
Advanced queries (#1041) should be fully case insensitive:
* keywords such as `and` should be accepted in any casing: `and`, `AND` and `aNd`.
  * make sure that metadata queries that contain a keyword are parsed correctly, e.g.: `my_and_field = my_or_value`)
* metadata field names should be case insensitive: `country = Germany` and `cOuNTry = Germany
  * The values of the metadata (right hand side of the `=`) queries should still remain case sensitive.
* The `.regex` modifier should also be case insensitive.
* Symbols in mutation and insertion queries should be case insensitive.

### PR DESCRIPTION
**Pull request by fengelniederhammer**
also refactor the test to make it easier to grasp what is already tested

resolves #1187

## PR Checklist
~~- [ ] All necessary documentation has been adapted.~~
- [x] The implemented feature is covered by an appropriate test.

### CODE REVIEW

File: lapis/src/main/kotlin/org/genspectrum/lapis/model/AdvancedQueryCustomListener.kt [hunk 1]
```diff
@@ -41,6 +42,14 @@ import java.time.LocalDate
 import java.time.format.DateTimeParseException
 import java.util.Locale
 import kotlin.collections.ArrayDeque
+import kotlin.collections.Map
```
Comment (anna-parker) [inline lapis/src/main/kotlin/org/genspectrum/lapis/model/AdvancedQueryCustomListener.kt:45]: Are these imports actually needed? I don't see any code changes in this file that would require them

File: lapis/src/test/kotlin/org/genspectrum/lapis/model/AdvancedQueryFacadeTest.kt [hunk 2]
```diff
@@ -237,26 +221,6 @@ class AdvancedQueryFacadeTest {
...
-    fun `GIVEN a advancedQuery with a mixed-case 'Maybe' expression THEN returns 'Maybe' SiloQuery`() {
-        val advancedQuery = "maYbE(T12C)"
-
-        val result = underTest.map(advancedQuery)
-
-        val expectedResult = Maybe(NucleotideSymbolEquals(null, 12, "C"))
-        assertThat(result, equalTo(expectedResult))
-    }
-
     @Test
```
Comment (anna-parker) [inline lapis/src/test/kotlin/org/genspectrum/lapis/model/AdvancedQueryFacadeTest.kt:224]: I find it odd to move the Maybe and not into the parametrized tests but not do the same for the `or` and `and`

File: lapis/src/main/kotlin/org/genspectrum/lapis/model/AdvancedQueryCustomListener.kt (hunk 1 above)
Comment (fengelniederhammer) [reply lapis/src/main/kotlin/org/genspectrum/lapis/model/AdvancedQueryCustomListener.kt:45]: That's weird, thanks for catching this. I don't know how they ended up there...

File: lapis/src/test/kotlin/org/genspectrum/lapis/model/AdvancedQueryFacadeTest.kt [hunk 3]
```diff
@@ -743,6 +639,82 @@ class AdvancedQueryFacadeTest {
                     "floatFieldTo=1",
                     "Metadata field floatFieldTo does not exist",
                 ),
+                InvalidTestCase(
```
Comment (anna-parker) [inline lapis/src/test/kotlin/org/genspectrum/lapis/model/AdvancedQueryFacadeTest.kt:642]: this should be added to the regexCases list

**Review by anna-parker — APPROVED** [review]
This is quite a refactor but as it doesn't seem to actually change much code I decided to just approve to not block too much - please check if all the additional imports are required though before merging
