### PR TITLE
fix: correctly map PangoLineageEquals filters

### LINKED ISSUE #201: Fix PangoLineage filter
A PangoLineage filter needs the field `include_sublineages`.

### PR DESCRIPTION
**Pull request by fengelniederhammer**
resolves #201 

This depends on https://github.com/GenSpectrum/LAPIS-SILO/pull/64.

### CODE REVIEW

File: lapis2/src/main/kotlin/org/genspectrum/lapis/model/AggregatedModel.kt [hunk 1]
```diff
@@ -25,19 +25,24 @@ class AggregatedModel(private val siloClient: SiloClient) {
...
-        "nucleotideMutations" -> generateNucleotideFilter(value)
+    fun mapToSiloFilter(key: String, value: String) = when (key) {
+        "pangoLineage" -> mapToPangoLineageFilter(value)
+        "nucleotideMutations" -> mapToNucleotideFilter(value)
         else -> StringEquals(key, value)
     }
 
-    private fun generateNucleotideFilter(userInput: String): SiloFilterExpression {
+    private fun mapToPangoLineageFilter(value: String) = when {
+        value.endsWith('*') -> PangoLineageEquals(value.substringBeforeLast('*'), includeSublineages = true)
```
Comment (chaoran-chen) [inline lapis2/src/main/kotlin/org/genspectrum/lapis/model/AggregatedModel.kt:41]: There is one subtlety here. It is possible to write both `BA.1*` and `BA.1.*`, they are considered completely equivalent.  Both should be mapped to "`BA.1` including sublineages".

**Review by chaoran-chen — CHANGES_REQUESTED** [review]

File: lapis2/src/main/kotlin/org/genspectrum/lapis/model/AggregatedModel.kt (hunk 1 above)
Comment (fengelniederhammer) [reply lapis2/src/main/kotlin/org/genspectrum/lapis/model/AggregatedModel.kt:41]: Should we handle this in LAPIS or in SILO?

My gut feeling says that we should push this to SILO and ignore it in LAPIS. SILO will need to do some validations and checks on this anyway.

Comment (chaoran-chen) [reply lapis2/src/main/kotlin/org/genspectrum/lapis/model/AggregatedModel.kt:41]: Do you mean that SILO should also accept `BA.1.` as a query? This could also be an option.

Then, we should at least add a test case in LAPIS to ensure (and document) that `BA.1.*` is a valid value.

Comment (fengelniederhammer) [reply lapis2/src/main/kotlin/org/genspectrum/lapis/model/AggregatedModel.kt:41]: What does `BA.1.` actually mean? Is it the same as `BA.1`?

Comment (chaoran-chen) [reply lapis2/src/main/kotlin/org/genspectrum/lapis/model/AggregatedModel.kt:41]: At the moment, `BA.1.` is not accepted (nothing will be found). However, `BA.1.*` is valid and means exactly the same as `BA.1*`. As SILO does not use the `*` syntax but requires an object with `{pango lineage, include sub-lineage}`, we have to decide how to map.

Suggestion 1:

- `BA.1` -> `{pango lineage: BA.1, include sub-lineage: false}`
- `BA.1.` -> Throw error message?
- `BA.1*` -> `{pango lineage: BA.1, include sub-lineage: true}`
- `BA.1.*` -> `{pango lineage: BA.1, include sub-lineage: true}`

Suggestion 2:

- `BA.1` -> `{pango lineage: BA.1, include sub-lineage: false}`
- `BA.1.` -> ???
- `BA.1*` -> `{pango lineage: BA.1, include sub-lineage: true}`
- `BA.1.*` -> `{pango lineage: BA.1., include sub-lineage: true}`

The constraint is, to maintain backward compatibility, that `BA.1*` and `BA.1.*` both work for LAPIS users and that they return the same.

I think that suggestion 1 is the easiest/most straight-forward but suggestion 2 is also okay.

Comment (chaoran-chen) [reply lapis2/src/main/kotlin/org/genspectrum/lapis/model/AggregatedModel.kt:41]: To be precise: `BA.1.` currently leads to somewhat inconsistent behavior. Used in a "simple" query, it does not cause an error but also does not return any sample. Used in an advanced variant query, it causes an error.

Comment (fengelniederhammer) [reply lapis2/src/main/kotlin/org/genspectrum/lapis/model/AggregatedModel.kt:41]: Suggestion 1 sounds reasonable, but I don't like that LAPIS needs to know quite a lot about the structure of a field. This might be hard to generalize.

**Review by chaoran-chen — APPROVED** [review]
Looks good, thanks!

**Review by JonasKellerer — APPROVED** [review]
