### PR TITLE
fix(lapis): also return CSV header when there are no data

### LINKED ISSUE #1090: Return CSV/TSV headers even when there are no data
@theosanderson discovered that apparently LAPIS doesn't return anything if the response is empty (for CSV/TSV format). It should at least print the headers.

### PR DESCRIPTION
**Pull request by fengelniederhammer**
resolves #1090

## PR Checklist
~~- [ ] All necessary documentation has been adapted.~~
- [x] The implemented feature is covered by an appropriate test.

### CODE REVIEW

File: lapis/src/main/kotlin/org/genspectrum/lapis/response/CsvWriter.kt [hunk 1]
```diff
@@ -1,59 +1,47 @@
...
-    @JsonIgnore
-    fun getHeader(comparator: Comparator<String>): List<String>
+    fun getHeader(): List<String>
+
+    fun getCsvRecords(): Stream<List<String?>> = records.map { mapToCsvValuesList(it) }
+
+    /**
+     * Csv values - must be in the same order as the header.
+     */
+    fun mapToCsvValuesList(value: T): List<String?>
```
Comment (JonasKellerer) [inline lapis/src/main/kotlin/org/genspectrum/lapis/response/CsvWriter.kt:18]: Is it possible to test this somehow for our specific collections in `ResponseCollections.kt`? Just to make sure that when we change things with the collections in the future, this will be still true.

File: lapis/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt [hunk 2]
```diff
@@ -1069,6 +1091,18 @@ class LapisController(
...
 
+    private fun getDetailsCollection(request: SequenceFiltersRequestWithFields): DetailsCollection {
+        val fields = request.fields.map { it.fieldName }
+
+        return DetailsCollection(
+            records = siloQueryModel.getDetails(request),
+            fields = when (fields.isEmpty()) {
+                true -> databaseConfig.schema.metadata.map { it.name }
+                false -> fields
+            },
```
Comment (JonasKellerer) [inline lapis/src/main/kotlin/org/genspectrum/lapis/controller/LapisController.kt:1102]: Good idea to put the sorting right here.

File: lapis/src/test/kotlin/org/genspectrum/lapis/controller/Helpers.kt [hunk 3]
```diff
@@ -53,3 +54,15 @@ fun sequenceFiltersRequestWithArrayValuedFilters(
...
     emptyList(),
 )
+
+fun MockHttpServletRequestBuilder.withFieldsQuery(fields: List<String>?) =
+    fields?.fold(this) { request, field -> request.queryParam("fields", field) } ?: this
+
+fun MockHttpServletRequestBuilder.withFieldsParam(fields: List<String>?) =
+    fields?.fold(this) { request, field -> request.param("fields", field) } ?: this
+
+fun getFieldsJsonPart(fields: List<String>?) =
```
Comment (JonasKellerer) [inline lapis/src/test/kotlin/org/genspectrum/lapis/controller/Helpers.kt:64]: Nitpick: I would name this `getFieldsAsJsonPart`.

File: lapis/src/test/resources/config/testDatabaseConfig.yaml [hunk 4]
```diff
@@ -15,6 +15,10 @@ schema:
       generateLineageIndex: true
     - name: test_boolean_column
       type: boolean
+    - name: age
```
Comment (JonasKellerer) [inline lapis/src/test/resources/config/testDatabaseConfig.yaml:18]: Nitpick: Should we name the int column also like the other columns: `test_int_column`, and not `age`. 
Also maybe not this PR, but we could also rename the other columns to fit the same format.

**Review by JonasKellerer — APPROVED** [review]
Nice work. There was more refactoring going on than I would have expected, but it looks good. 
Only some minor issues.

File: lapis/src/main/kotlin/org/genspectrum/lapis/response/ResponseCollections.kt [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+class MutationsCollection(
+    override val records: Stream<MutationResponse>,
+) : RecordCollection<MutationResponse> {
+    override fun getHeader() =
+        listOf(
+            "mutation",
+            "count",
+            "coverage",
+            "proportion",
+            "sequenceName",
```
[the remark this answers is not in the document]
Comment (fengelniederhammer) [reply lapis/src/main/kotlin/org/genspectrum/lapis/response/ResponseCollections.kt:45]: I think "sequenceName" is a good generic term for both, gene and segment. Anyway that would be a breaking change, so I'll ignore this here.

File: lapis/src/main/kotlin/org/genspectrum/lapis/response/CsvWriter.kt (hunk 1 above)
Comment (fengelniederhammer) [reply lapis/src/main/kotlin/org/genspectrum/lapis/response/CsvWriter.kt:18]: The tests that check the CSVs of insertions and mutations implicitly test that already.

File: lapis/src/test/resources/config/testDatabaseConfig.yaml (hunk 4 above)
Comment (fengelniederhammer) [reply lapis/src/test/resources/config/testDatabaseConfig.yaml:18]: Sounds like a good idea, but I'll leave that to a separate PR, if someone has time.
